### PR TITLE
Shutting down repo and redirecting users to DAGMC.

### PR DESCRIPTION
**Pull request by pshriwise**

### CODE REVIEW

**Comment by gonuke** [comment]
Sorry to be pedantic, but I think we should merge `develop` into `master` first, and then merge this PR into `master`.

We should tag `master` as a release before we merge this PR.

**Comment by Pshriwise** [comment]
Good idea. I'm on board. Maybe a tag like `dagmc_move`? Make_watertight has never really had version numbers that I'm aware of.

**Comment by gonuke** [comment]
Correct - maybe `before_dagmc_move` and then add a reference to that tag in the README that will be there after the move.

**Comment by Pshriwise** [comment]
Sounds good. So we need to PR develop into master then? Is that typically done from within Svalinn or can it be done from a fork? The history would be the same either way, but it might look weird to have a merge into master coming from a fork...

**Comment by Pshriwise** [comment]
FWIW both merging the develop branch into master and pushing the appropriate tag (which we should probably annotate btw) are restricted to me in this repository and will need to be done by either @gonuke or @makeclean

**Comment by gonuke** [comment]
Not any more :smile:

**Comment by Pshriwise** [comment]
Had to deal with some conflicts, but the head of develop was tagged with the `before_dagmc_move` tag, develop was merged into master and I've updated this PR to go straight into master now.

**Comment by gonuke** [comment]
So finally... update the new README to indicate which release should be used to capture the last version of the previous repo.  Something like:

"The final version of this repo can be accessed via the `before_dagmc_move` release."

**Comment by Pshriwise** [comment]
Yup, forgot that bit. Just took care of it.

**Comment by gonuke** [comment]
Thanks @Pshriwise

**Pull request merged**
